# Generated by Django 4.2 on 2023-05-03 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merch',
            name='hot_item',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='merch',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_cat', to='store.category'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_col', to='store.collection'),
        ),
    ]
