# Generated by Django 4.2 on 2023-05-02 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xsmall', models.BooleanField(blank=True, default=False, null=True, verbose_name='X-Small')),
                ('small', models.BooleanField(blank=True, default=False, null=True, verbose_name='Small')),
                ('medium', models.BooleanField(blank=True, default=False, null=True, verbose_name='Medium')),
                ('large', models.BooleanField(blank=True, default=False, null=True, verbose_name='Large')),
                ('xlarge', models.BooleanField(blank=True, default=False, null=True, verbose_name='X-Large')),
                ('xxlarge', models.BooleanField(blank=True, default=False, null=True, verbose_name='XX-Large')),
            ],
        ),
        migrations.AddField(
            model_name='merch',
            name='sizes_available',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_size', to='store.size'),
        ),
    ]
