# Generated by Django 4.2 on 2023-05-02 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_size_merch_sizes_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merch',
            name='sizes_available',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
