# Generated by Django 4.2 on 2023-05-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_merch_hot_item_alter_merch_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='hot_item',
            field=models.BooleanField(default=False),
        ),
    ]
