# Generated by Django 4.2 on 2023-05-02 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_merch_sizes_available_delete_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_col', to='store.collection'),
        ),
    ]
