# Generated by Django 4.2 on 2023-05-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_merch_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='merch',
            name='in_stock',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
