# Generated by Django 4.2 on 2023-05-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_merch_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
