# Generated by Django 4.2 on 2023-05-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_orderitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.AddField(
            model_name='order',
            name='billing_status',
            field=models.BooleanField(default=False),
        ),
    ]
